apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kledeli-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: kledeli.nheek.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kledeli-service
            port:
              number: 30100