-- Create a database if it doesn't exist
CREATE DATABASE IF NOT EXISTS kledeli;

-- Create a user and grant privileges
CREATE USER '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON kledeli.* TO '${MYSQL_USER}'@'localhost';

-- Flush privileges to apply the changes immediately
FLUSH PRIVILEGES;

-- Use the created database
USE kledeli;

CREATE TABLE IF NOT EXISTS Clothes (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `img` varchar(100) DEFAULT NULL,
  `typeOf` varchar(50) DEFAULT NULL,
  `stock` int(11) DEFAULT NULL,
  `sizes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`sizes`)),
  `link` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS PickupLocs (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `address` varchar(200) DEFAULT NULL,
  `description` tinytext DEFAULT NULL,
  `map` text DEFAULT NULL,
  `area` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS Subscriptions (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `price` int(11) DEFAULT NULL,
  `features` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`features`)),
  `icon` varchar(100) DEFAULT NULL,
  `max_item` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS Users (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(150) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `username` varchar(100) DEFAULT NULL,
  `mobile_no` varchar(100) DEFAULT NULL,
  `password` varchar(200) DEFAULT NULL,
  `subscription_id` int(11) DEFAULT NULL,
  `pickup_loc_id` int(11) DEFAULT NULL,
  `wardrobe_items` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`wardrobe_items`)),
  `wardrobe_items_sizes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO `Clothes` (`id`, `name`, `img`, `typeOf`, `stock`, `sizes`, `link`, `description`, `gender`) VALUES
(1,	'Rosa Hansker',	'/uploads/catalog/hanske.png',	'ytterklaer',	10,	'[\"S\", \"M\", \"L\"]',	'rosa-hansker',	'Mauris varius dolor et risus mollis, a aliquam purus laoreet. Quisque tempor felis id nunc commodo, sit amet semper elit pharetra. Nulla malesuada fermentum pulvinar. Fusce nibh mi, suscipit nec laoreet sit amet, viverra id tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum iaculis pharetra ex, a facilisis turpis tincidunt et. Pellentesque ullamcorper vel lorem et mattis.',	'jente'),
(2,	'Svart Hansker',	'/uploads/catalog/hanske1.png',	'ytterklaer',	10,	'[\"S\", \"M\", \"L\"]',	'svart-hansker',	'Mauris varius dolor et risus mollis, a aliquam purus laoreet. Quisque tempor felis id nunc commodo, sit amet semper elit pharetra. Nulla malesuada fermentum pulvinar. Fusce nibh mi, suscipit nec laoreet sit amet, viverra id tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum iaculis pharetra ex, a facilisis turpis tincidunt et. Pellentesque ullamcorper vel lorem et mattis.',	'gutt'),
(3,	'Blå lue',	'/uploads/catalog/hue.png',	'ytterklaer',	10,	'[\"S\", \"M\", \"L\"]',	'bla-lue',	'Mauris varius dolor et risus mollis, a aliquam purus laoreet. Quisque tempor felis id nunc commodo, sit amet semper elit pharetra. Nulla malesuada fermentum pulvinar. Fusce nibh mi, suscipit nec laoreet sit amet, viverra id tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum iaculis pharetra ex, a facilisis turpis tincidunt et. Pellentesque ullamcorper vel lorem et mattis.',	'jente'),
(4,	'Brunn lue',	'/uploads/catalog/hue1.png',	'ytterklaer',	10,	'[\"S\", \"M\", \"L\"]',	'brunn-lue',	'Mauris varius dolor et risus mollis, a aliquam purus laoreet. Quisque tempor felis id nunc commodo, sit amet semper elit pharetra. Nulla malesuada fermentum pulvinar. Fusce nibh mi, suscipit nec laoreet sit amet, viverra id tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum iaculis pharetra ex, a facilisis turpis tincidunt et. Pellentesque ullamcorper vel lorem et mattis.',	'gutt'),
(5,	'Blå jakke',	'/uploads/catalog/jakke.png',	'ytterklaer',	10,	'[\"S\", \"M\", \"L\"]',	'blaa-jakke',	'Mauris varius dolor et risus mollis, a aliquam purus laoreet. Quisque tempor felis id nunc commodo, sit amet semper elit pharetra. Nulla malesuada fermentum pulvinar. Fusce nibh mi, suscipit nec laoreet sit amet, viverra id tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum iaculis pharetra ex, a facilisis turpis tincidunt et. Pellentesque ullamcorper vel lorem et mattis.',	'jente'),
(6,	'Grå jakke',	'/uploads/catalog/jakke1.png',	'ytterklaer',	10,	'[\"S\", \"M\", \"L\"]',	'graa-jakke',	'Mauris varius dolor et risus mollis, a aliquam purus laoreet. Quisque tempor felis id nunc commodo, sit amet semper elit pharetra. Nulla malesuada fermentum pulvinar. Fusce nibh mi, suscipit nec laoreet sit amet, viverra id tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum iaculis pharetra ex, a facilisis turpis tincidunt et. Pellentesque ullamcorper vel lorem et mattis.',	'gutt'),
(7,	'Grønn dress',	'/uploads/catalog/parkdress.png',	'ytterklaer',	10,	'[\"S\", \"M\", \"L\"]',	'groen-dress',	'Mauris varius dolor et risus mollis, a aliquam purus laoreet. Quisque tempor felis id nunc commodo, sit amet semper elit pharetra. Nulla malesuada fermentum pulvinar. Fusce nibh mi, suscipit nec laoreet sit amet, viverra id tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum iaculis pharetra ex, a facilisis turpis tincidunt et. Pellentesque ullamcorper vel lorem et mattis.',	'jente'),
(8,	'Blå dress',	'/uploads/catalog/parkdress1.png',	'ytterklaer',	10,	'[\"S\", \"M\", \"L\"]',	'blaa-dress',	'Mauris varius dolor et risus mollis, a aliquam purus laoreet. Quisque tempor felis id nunc commodo, sit amet semper elit pharetra. Nulla malesuada fermentum pulvinar. Fusce nibh mi, suscipit nec laoreet sit amet, viverra id tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum iaculis pharetra ex, a facilisis turpis tincidunt et. Pellentesque ullamcorper vel lorem et mattis.',	'gutt'),
(9,	'Blå bukse',	'/uploads/catalog/bukse1.png',	'indreklaer',	10,	'[\"S\", \"M\", \"L\"]',	'blaa-bukse',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at est sit amet felis sodales vestibulum. Vestibulum egestas nunc eget nunc tincidunt, non auctor orci volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus mollis erat lobortis ex interdum, non feugiat ante sodales. Sed neque purus, dapibus at rhoncus eget, posuere ac lacus. Phasellus rutrum lorem sit amet risus finibus dapibus vitae vel ligula. Vivamus risus ex, gravida sit amet rhoncus ac, fringilla ac eros. In molestie pellentesque arcu ut pharetra. Nam massa tortor, sollicitudin quis felis non, molestie vulputate sem.\r\n\r\n',	'gutt'),
(10,	'Grønn bukse',	'/uploads/catalog/bukse2.png',	'indreklaer',	10,	'[\"S\", \"M\", \"L\"]',	'groen-bukse',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at est sit amet felis sodales vestibulum. Vestibulum egestas nunc eget nunc tincidunt, non auctor orci volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus mollis erat lobortis ex interdum, non feugiat ante sodales. Sed neque purus, dapibus at rhoncus eget, posuere ac lacus. Phasellus rutrum lorem sit amet risus finibus dapibus vitae vel ligula. Vivamus risus ex, gravida sit amet rhoncus ac, fringilla ac eros. In molestie pellentesque arcu ut pharetra. Nam massa tortor, sollicitudin quis felis non, molestie vulputate sem.\r\n\r\n',	'jente'),
(11,	'Grønn genser',	'/uploads/catalog/genser.png',	'indreklaer',	10,	'[\"S\", \"M\", \"L\"]',	'groen-genser',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at est sit amet felis sodales vestibulum. Vestibulum egestas nunc eget nunc tincidunt, non auctor orci volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus mollis erat lobortis ex interdum, non feugiat ante sodales. Sed neque purus, dapibus at rhoncus eget, posuere ac lacus. Phasellus rutrum lorem sit amet risus finibus dapibus vitae vel ligula. Vivamus risus ex, gravida sit amet rhoncus ac, fringilla ac eros. In molestie pellentesque arcu ut pharetra. Nam massa tortor, sollicitudin quis felis non, molestie vulputate sem.\r\n\r\n',	'gutt'),
(12,	'Rosa genser',	'/uploads/catalog/genser2.png',	'indreklaer',	10,	'[\"S\", \"M\", \"L\"]',	'rosa-genser',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at est sit amet felis sodales vestibulum. Vestibulum egestas nunc eget nunc tincidunt, non auctor orci volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus mollis erat lobortis ex interdum, non feugiat ante sodales. Sed neque purus, dapibus at rhoncus eget, posuere ac lacus. Phasellus rutrum lorem sit amet risus finibus dapibus vitae vel ligula. Vivamus risus ex, gravida sit amet rhoncus ac, fringilla ac eros. In molestie pellentesque arcu ut pharetra. Nam massa tortor, sollicitudin quis felis non, molestie vulputate sem.\r\n\r\n',	'jente'),
(15,	'Blå skjorte',	'/uploads/catalog/skjorte.png',	'indreklaer',	10,	'[\"S\", \"M\", \"L\"]',	'blaa-skjorte',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at est sit amet felis sodales vestibulum. Vestibulum egestas nunc eget nunc tincidunt, non auctor orci volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus mollis erat lobortis ex interdum, non feugiat ante sodales. Sed neque purus, dapibus at rhoncus eget, posuere ac lacus. Phasellus rutrum lorem sit amet risus finibus dapibus vitae vel ligula. Vivamus risus ex, gravida sit amet rhoncus ac, fringilla ac eros. In molestie pellentesque arcu ut pharetra. Nam massa tortor, sollicitudin quis felis non, molestie vulputate sem.\r\n\r\n',	'gutt'),
(16,	'Brunn skjorte',	'/uploads/catalog/skjorte1.png',	'indreklaer',	10,	'[\"S\", \"M\", \"L\"]',	'brunn-skjorte',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at est sit amet felis sodales vestibulum. Vestibulum egestas nunc eget nunc tincidunt, non auctor orci volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus mollis erat lobortis ex interdum, non feugiat ante sodales. Sed neque purus, dapibus at rhoncus eget, posuere ac lacus. Phasellus rutrum lorem sit amet risus finibus dapibus vitae vel ligula. Vivamus risus ex, gravida sit amet rhoncus ac, fringilla ac eros. In molestie pellentesque arcu ut pharetra. Nam massa tortor, sollicitudin quis felis non, molestie vulputate sem.\r\n\r\n',	'jente'),
(24,	'Blå body',	'/uploads/catalog/body.png',	'undertoey',	10,	'[\"S\", \"M\", \"L\"]',	'blaa-body',	'Vivamus ipsum augue, vehicula quis gravida ac, fringilla vitae metus. Aenean accumsan gravida dui, quis fringilla augue aliquet sit amet. Mauris vel iaculis nulla. In id ultricies ante. Morbi consequat libero nisl, a vestibulum orci tempor in. Donec ligula purus, iaculis non lacus sit amet, condimentum ultricies ligula. Suspendisse diam urna, mollis ac interdum sed, sodales eu felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce faucibus faucibus urna a consequat. Cras mattis lorem at turpis vulputate, eget lacinia elit mollis. Sed pellentesque mauris porta, lacinia ex at, vulputate arcu. Cras blandit tortor sed tortor facilisis fringilla. Suspendisse potenti. Nam porttitor odio sem, sit amet pellentesque augue faucibus at. Suspendisse ultricies semper dui efficitur dignissim.\r\n\r\n',	'gutt'),
(25,	'Grønn body',	'/uploads/catalog/body1.png',	'undertoey',	10,	'[\"S\", \"M\", \"L\"]',	'groen-body',	'Vivamus ipsum augue, vehicula quis gravida ac, fringilla vitae metus. Aenean accumsan gravida dui, quis fringilla augue aliquet sit amet. Mauris vel iaculis nulla. In id ultricies ante. Morbi consequat libero nisl, a vestibulum orci tempor in. Donec ligula purus, iaculis non lacus sit amet, condimentum ultricies ligula. Suspendisse diam urna, mollis ac interdum sed, sodales eu felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce faucibus faucibus urna a consequat. Cras mattis lorem at turpis vulputate, eget lacinia elit mollis. Sed pellentesque mauris porta, lacinia ex at, vulputate arcu. Cras blandit tortor sed tortor facilisis fringilla. Suspendisse potenti. Nam porttitor odio sem, sit amet pellentesque augue faucibus at. Suspendisse ultricies semper dui efficitur dignissim.\r\n\r\n',	'jente'),
(26,	'Grønn t-skjorte',	'/uploads/catalog/tskjorte.png',	'undertoey',	10,	'[\"S\", \"M\", \"L\"]',	'groen-tskjorte',	'Vivamus ipsum augue, vehicula quis gravida ac, fringilla vitae metus. Aenean accumsan gravida dui, quis fringilla augue aliquet sit amet. Mauris vel iaculis nulla. In id ultricies ante. Morbi consequat libero nisl, a vestibulum orci tempor in. Donec ligula purus, iaculis non lacus sit amet, condimentum ultricies ligula. Suspendisse diam urna, mollis ac interdum sed, sodales eu felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce faucibus faucibus urna a consequat. Cras mattis lorem at turpis vulputate, eget lacinia elit mollis. Sed pellentesque mauris porta, lacinia ex at, vulputate arcu. Cras blandit tortor sed tortor facilisis fringilla. Suspendisse potenti. Nam porttitor odio sem, sit amet pellentesque augue faucibus at. Suspendisse ultricies semper dui efficitur dignissim.\r\n\r\n',	'gutt'),
(27,	'Svart t-skjorte',	'/uploads/catalog/tskjorte1.png',	'undertoey',	10,	'[\"S\", \"M\", \"L\"]',	'svart-tskjorte',	'Vivamus ipsum augue, vehicula quis gravida ac, fringilla vitae metus. Aenean accumsan gravida dui, quis fringilla augue aliquet sit amet. Mauris vel iaculis nulla. In id ultricies ante. Morbi consequat libero nisl, a vestibulum orci tempor in. Donec ligula purus, iaculis non lacus sit amet, condimentum ultricies ligula. Suspendisse diam urna, mollis ac interdum sed, sodales eu felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce faucibus faucibus urna a consequat. Cras mattis lorem at turpis vulputate, eget lacinia elit mollis. Sed pellentesque mauris porta, lacinia ex at, vulputate arcu. Cras blandit tortor sed tortor facilisis fringilla. Suspendisse potenti. Nam porttitor odio sem, sit amet pellentesque augue faucibus at. Suspendisse ultricies semper dui efficitur dignissim.\r\n\r\n',	'jente'),
(28,	'Rød ullbukse',	'/uploads/catalog/ullbukse.png',	'undertoey',	10,	'[\"S\", \"M\", \"L\"]',	'roed-ullbukse',	'Vivamus ipsum augue, vehicula quis gravida ac, fringilla vitae metus. Aenean accumsan gravida dui, quis fringilla augue aliquet sit amet. Mauris vel iaculis nulla. In id ultricies ante. Morbi consequat libero nisl, a vestibulum orci tempor in. Donec ligula purus, iaculis non lacus sit amet, condimentum ultricies ligula. Suspendisse diam urna, mollis ac interdum sed, sodales eu felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce faucibus faucibus urna a consequat. Cras mattis lorem at turpis vulputate, eget lacinia elit mollis. Sed pellentesque mauris porta, lacinia ex at, vulputate arcu. Cras blandit tortor sed tortor facilisis fringilla. Suspendisse potenti. Nam porttitor odio sem, sit amet pellentesque augue faucibus at. Suspendisse ultricies semper dui efficitur dignissim.\r\n\r\n',	'gutt'),
(29,	'Rosa ullbukse',	'/uploads/catalog/ullbukse1.png',	'undertoey',	10,	'[\"S\", \"M\", \"L\"]',	'rosa-ullbukse',	'Vivamus ipsum augue, vehicula quis gravida ac, fringilla vitae metus. Aenean accumsan gravida dui, quis fringilla augue aliquet sit amet. Mauris vel iaculis nulla. In id ultricies ante. Morbi consequat libero nisl, a vestibulum orci tempor in. Donec ligula purus, iaculis non lacus sit amet, condimentum ultricies ligula. Suspendisse diam urna, mollis ac interdum sed, sodales eu felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce faucibus faucibus urna a consequat. Cras mattis lorem at turpis vulputate, eget lacinia elit mollis. Sed pellentesque mauris porta, lacinia ex at, vulputate arcu. Cras blandit tortor sed tortor facilisis fringilla. Suspendisse potenti. Nam porttitor odio sem, sit amet pellentesque augue faucibus at. Suspendisse ultricies semper dui efficitur dignissim.\r\n\r\n',	'jente'),
(30,	'Grå ullgenser',	'/uploads/catalog/ullgenser.png',	'undertoey',	10,	'[\"S\", \"M\", \"L\"]',	'graa-ullgenser',	'Vivamus ipsum augue, vehicula quis gravida ac, fringilla vitae metus. Aenean accumsan gravida dui, quis fringilla augue aliquet sit amet. Mauris vel iaculis nulla. In id ultricies ante. Morbi consequat libero nisl, a vestibulum orci tempor in. Donec ligula purus, iaculis non lacus sit amet, condimentum ultricies ligula. Suspendisse diam urna, mollis ac interdum sed, sodales eu felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce faucibus faucibus urna a consequat. Cras mattis lorem at turpis vulputate, eget lacinia elit mollis. Sed pellentesque mauris porta, lacinia ex at, vulputate arcu. Cras blandit tortor sed tortor facilisis fringilla. Suspendisse potenti. Nam porttitor odio sem, sit amet pellentesque augue faucibus at. Suspendisse ultricies semper dui efficitur dignissim.\r\n\r\n',	'gutt'),
(31,	'Rød ullgenser',	'/uploads/catalog/ullgenser1.png',	'undertoey',	10,	'[\"S\", \"M\", \"L\"]',	'roed-ullgenser',	'Vivamus ipsum augue, vehicula quis gravida ac, fringilla vitae metus. Aenean accumsan gravida dui, quis fringilla augue aliquet sit amet. Mauris vel iaculis nulla. In id ultricies ante. Morbi consequat libero nisl, a vestibulum orci tempor in. Donec ligula purus, iaculis non lacus sit amet, condimentum ultricies ligula. Suspendisse diam urna, mollis ac interdum sed, sodales eu felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce faucibus faucibus urna a consequat. Cras mattis lorem at turpis vulputate, eget lacinia elit mollis. Sed pellentesque mauris porta, lacinia ex at, vulputate arcu. Cras blandit tortor sed tortor facilisis fringilla. Suspendisse potenti. Nam porttitor odio sem, sit amet pellentesque augue faucibus at. Suspendisse ultricies semper dui efficitur dignissim.\r\n\r\n',	'jente');

INSERT INTO `PickupLocs` (`name`, `address`, `description`, `map`, `area`) VALUES
('Pakkeboks Kiwi Bøhmergaten', 'Bøhmergaten 44, 5057 Bergen', 'Pakkeboksen står plassert bak på høyresiden av bygget.', '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d63110.52442910068!2d5.334259003451742!3d60.3757917105875!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x463cf94ebb546bff%3A0xd2f3ceea1dba624b!2sPakkeboks%20KIWI%20B%C3%B8hmergaten!5e0!3m2!1sen!2sno!4v1695299082733!5m2!1sen!2sno" width="100%" height="200" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', 'Bergen'),
('Pakkeautomat Fanavegen', 'Fanavegen 83, 5239 Rådal', 'Pakkeboksen står plassert foran Rema 1000', '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1044.444869510047!2d5.344927596095116!3d60.30958660195474!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x463cf9c0e3f693a9%3A0x4a3714ab837cb68d!2sREMA%201000%20SKJOLD!5e0!3m2!1sen!2sno!4v1695296628911!5m2!1sen!2sno" width="100%" height="200" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', 'Bergen'),
('Pakkeboks Bergen Jernbanestasjon', 'Strømgaten 4, 5015 Bergen', 'Pakkeboksen står mellom Narvesen og billettautomaten, ved inngangen som fører til Bystasjonen.', '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1971.3375149655462!2d5.330654277182518!3d60.39010307514533!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x463cff0381f9a6b1%3A0x45a24c210e74dbcc!2sPakkeboks%20Bergen%20Jernbanestasjon!5e0!3m2!1sen!2sno!4v1695299293752!5m2!1sen!2sno" width="100%" height="200" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', 'Bergen'),
('Pakkeboks Åsane Senter 12', 'Åsane Senter 12, 5116 Ulset', 'Pakkeautomaten står plassert i nederste etasje, midt i gamle Arken.', '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1971.3375149655462!2d5.330654277182518!3d60.39010307514533!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x463cff0381f9a6b1%3A0x45a24c210e74dbcc!2sPakkeboks%20Bergen%20Jernbanestasjon!5e0!3m2!1sen!2sno!4v1695299293752!5m2!1sen!2sno" width="100%" height="200" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', 'Bergen');

INSERT INTO `Subscriptions` (`id`, `name`, `price`, `features`, `icon`, `max_item`) VALUES
(1,	'10-plagg',	1200,	'[\"Rimelig\", \"Bruk i 3 måneder\"]',	'/uploads/sub/ultra-pro-max-max.png',	10),
(2,	'8-plagg',	900,	'[\"Rimelig\", \"Bruk i 3 måneder\"]',	'/uploads/sub/ultra.png',	8),
(3,	'5-plagg',	700,	'[\"Rimelig\", \"Bruk i 3 måneder\"]',	'/uploads/sub/ultra-pro-max1.png',	5),
(4,	'3-plagg',	500,	'[\"Rimelig\", \"Bruk i 3 måneder\"]',	'/uploads/sub/premium.png',	3);